[package]
name = "bin"
version = "1.0.0"
authors = ["Yang Sheng Han <progamesigner@gmail.com>"]
edition = "2018"

[[bin]]
name = "apply"
path = "apply.rs"

[[bin]]
name = "contact"
path = "contact.rs"

[dependencies]
actix-web = "1.0"
api = { path = "../api" }
http = "0.1"
now_lambda = "0.1"
