name: Build and publish to GitHub Packages

on:
  push:
    branches:
    - master
  release:
    types:
    - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        IMAGE=ghcr.io/${{ github.repository_owner }}/rfgames-contact-api-server
        VERSION=""
        if [[ "${{ github.ref }}" == refs/tags/v* ]]; then
          VERSION=$(echo ${{ github.ref }} | sed -e 's/^refs\/tags\/v//g')
        elif [[ "${{ github.ref }}" == refs/pull/* ]]; then
          VERSION=pr-${{ github.event.number }}
        else
          VERSION=latest
        fi
        TAGS=${IMAGE}:${VERSION},${IMAGE}:${{ github.sha }}
        if [[ "${{ github.event_name }}" == push ]]; then
          TAGS=${TAGS},${IMAGE}:sha-$(echo ${{ github.sha }} | sed 's/^\(.\{6\}\).*/\1/g')
        fi
        echo IMAGE_CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ') >> $GITHUB_ENV
        echo IMAGE_TAGS=${TAGS} >> $GITHUB_ENV
        echo IMAGE_VERSION=${VERSION} >> $GITHUB_ENV
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        password: ${{ secrets.REGISTRY_TOKEN }}
        registry: ghcr.io
        username: ${{ github.repository_owner }}
    - uses: docker/build-push-action@v2
      with:
        build-args: |
          BUILD_TARGET=contact
        labels: |
          org.opencontainers.image.authors=Yang Sheng Han <https://progamesigner.com>
          org.opencontainers.image.created=${{ env.IMAGE_CREATED }}
          org.opencontainers.image.description=High performance RFGames API backend implemented in Rust.
          org.opencontainers.image.documentation=${{ github.event.repository.html_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=${{ github.event.repository.html_url }}
          org.opencontainers.image.title=${{ github.repository_owner }}/rfgames-contact-api-server
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.vendor=https://github.com/${{ github.repository_owner }}
          org.opencontainers.image.version=${{ env.IMAGE_VERSION }}
        push: true
        tags: ${{ env.IMAGE_TAGS }}
